sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_cb050a24e2ad_key -iv $encrypted_cb050a24e2ad_iv -in serviceAcountGCP.json.enc -out serviceAcountGCP.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  
  
